import { ICanopy } from './imodel/i-canopy';
import { IBays } from './imodel/ibays';
import { IBracing } from './imodel/ibracing';
import { IBuildingGeometry } from './imodel/ibuilding-geometry';
//import { ICanopy } from './imodel/i-canopy';
import { IColumns } from './imodel/icolumns';
import { IEndwalls } from './imodel/iendwalls';
import { IEWPlaza } from './imodel/iewplaza';
import { IEWRecess } from './imodel/iewrecess';
import { IFramelines } from './Imodel/iframelines';
import { IGroups } from './imodel/igroups';
//import { ISidewalls } from './imodel/i-sidewalls';
//import { ISpecifiedGirts } from './imodel/i-specifiedgirts';
//import { IXBraceAnchor } from './imodel/i-xbrace-anchor';
import { IModules } from './imodel/imodules';
//import { ISpecifiedPurlins } from './imodel/i-specifiedpurlins';
import { IOOpenArea } from './imodel/IO_OpenAreas';
//import { IOPartitions } from './iomodel/io_partitions';
import { IOSoldierColumns } from './imodel/io_soldiercolumns';
//import { IOLouvers } from './iomodel/io_louvers';
//import { IOPartitionSpacing } from './iomodel/io-partitionspacing';
//import { IPointLoads } from './imodel/i-point-loads';
//import { IOFramedOpenings } from './iomodel/io-framed-openings';
//import { IOTranslucentPanels } from './iomodel/io-translucent-panels';
//import { IOVents } from './iomodel/io-vents';
//import { IOSlideDoors } from './iomodel/io-slidedoors';
//import { IOParapets } from './iomodel/io_parapets';
//import { IOFacades } from './iomodel/io_facades';
//import { IOWindows } from './iomodel/io-windows';
//import { IODoors } from './iomodel/io-doors';
//import { IODBCIDoors } from './building-drawing-classes/IO_DBCIDoors';
//import { IOLiners } from './iomodel/IO_Liners';
//import { IOSupportBeams } from './iomodel/io_supportBeams';
//import { IOGlassFront } from './iomodel/IO_GlassFront';
//import { ICranes } from './imodel/i-cranes';
//import { IOMezzanineOpenings, IOMezzanines, IOMezzanineSpacing } from './iomodel/io-mezzanines';

export class IBuildingData {
  //ITable
  public IBuildingGeometry: IBuildingGeometry[];
  public IFramelines: IFramelines[];
  public IGroups: IGroups[];
  public IColumns: IColumns[];
  public IModules: IModules[];
  public IEndwalls: IEndwalls[];
  //public ISidewalls: ISidewalls[];
  public IBays: IBays[];
  //public ISpecifiedGirts: ISpecifiedGirts[];
  //public ISpecifiedPurlins: ISpecifiedPurlins[];
  public IEWRecess: IEWRecess[];
  public IBracing: IBracing[];
  public IEWPlaza: IEWPlaza[];
  public ICanopy: ICanopy[];
  //public IXBraceAnchor: IXBraceAnchor[];
  //public IPointLoads: IPointLoads[];

  public IOSoldierColumns: IOSoldierColumns[];
  public IOOpenArea: IOOpenArea[];
  //public IOPartitions: IOPartitions[];
  //public IOLouvers: IOLouvers[];
  //public IOPartitionSpacing: IOPartitionSpacing[];
  //public IOFramedOpenings: IOFramedOpenings[];
  //public IOTranslucentPanels: IOTranslucentPanels[];
  //public IOVents: IOVents[];
  //public IOSlideDoors: IOSlideDoors[];
  //public IOParapets: IOParapets[];
  //public IOFacades: IOFacades[];
  //public IOWindows: IOWindows[];
  //public IODoors: IODoors[];
  //public IODBCIDoors: IODBCIDoors[];
  //public IOLiners: IOLiners[];
  //public IOSupportBeams: IOSupportBeams[];
  //public IOGlassFront: IOGlassFront[];
  //public ICranes: ICranes[];
  //public IOMezzanines: IOMezzanines[];
  //public IOMezzanineOpenings: IOMezzanineOpenings[];
  //public IOMezzanineSpacing: IOMezzanineSpacing[];
}
